#!/usr/bin/perl -w

use strict;
use FindBin;
use lib "$FindBin::Bin/../perllib";

use Games::Checkers::Constants;
use Games::Checkers::MoveConstants;
use Games::Checkers::BoardTree;

my $board = Games::Checkers::Board->new;
my $color = White;

my $boardNode = Games::Checkers::BoardTreeNode->new($board, NO_MOVE);

my $countingMoves = Games::Checkers::CountMoveList->new($board, $color);
die "Internal problem" unless $countingMoves->{status} == Ok;
print "There are ", $countingMoves->getCount, " possible initial moves.\n";

my $creatingMoves = Games::Checkers::CreateMoveList->new($boardNode, $color);
die "Internal problem" unless $creatingMoves->{status} == Ok;

print $board->dump;

foreach (@{$boardNode->{sons}}) {
	print "-" x 78, "\n\n";
	print "Move: ", $_->{move}->dump, "\n";
	print $_->dump, "\n";
}
